In [16]:
#데이터 핸들링 툴
import numpy as np
import pandas as pd

In [2]:
list2=[1,2,'test']
array2=np.array(list2)
print(array2,array2.dtype)

list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [4]:
arr1= np.array([1,2,3,4,5,6,7,8,9])
print(arr1>5)

[False False False False False  True  True  True  True]


In [5]:
name_arr=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_arr=np.array([78,95,84,98,88])

sorted_idx=np.argsort(score_arr)
print('성적 오름차순으로 이름을 출력합니다:',name_arr[sorted_idx])

성적 오름차순으로 이름을 출력합니다: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [9]:
#타이타닉 데이터 다루기
titanic_df=pd.read_csv('./train.csv')
print('DataFrame의 크기',titanic_df.shape) # 샘플 포인트가 891개, 컬럼이 12개
titanic_df.head(10)

DataFrame의 크기 (891, 12)


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [10]:
#타이타닉 컬럼의 정보
titanic_df.info() # 누락된 데이터 없음, 정수,실수등이 있지만, 객체(변수들이 혼합된 형태)가 존재

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [12]:
#타이타닉 컬럼의 통계량
titanic_df.describe() # 데이터 갯수, 평균,표준편차,사분위수: 최대-최소,25%,75% 가 출력된다
                     #다만 여기서 category를 정수로 표현한 PassengerId,Pclass,Survived등은 이 통계량은 아무 의미도 없다

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [14]:
#각 컬럼의 카테고리 별 갯수 파악하기
counts= titanic_df['Pclass'].value_counts()
print(type(counts))
print(counts)

<class 'pandas.core.series.Series'>
3    491
1    216
2    184
Name: Pclass, dtype: int64


In [20]:
col_name= ['col1']
lst1=[1,2,3]
arr1=np.array(lst1)
print('array1 shape:',arr1.shape)
#리스트를 통해 데이터 프레임 생성
df_lst=pd.DataFrame(lst1,columns=col_name)
print('1차원 리스트를 통해 데이터프레임 생성: \n',df_lst)
#넘파이 ndarray를 통해 데이터 프레임 생성
df_arr= pd.DataFrame(arr1,columns=col_name)
print('1차원 ndarray를 통해 데이터프레임 생성 \n',df_arr)

array1 shape: (3,)
1차원 리스트를 통해 데이터프레임 생성: 
    col1
0     1
1     2
2     3
1차원 ndarray를 통해 데이터프레임 생성 
    col1
0     1
1     2
2     3


In [19]:
#3개의 컬럼명을 사용함
col_name= ['col1','col2','col3']
lst2=[[1,2,3],[11,12,13]]
arr2=np.array(lst2)
df_lst2=pd.DataFrame(lst2,columns=col_name)
df_arr2=pd.DataFrame(arr2,columns=col_name)
print('2차원 리스트로 만든 데이터프레임 \n',df_lst2)
print('2차원 넘파이 배열로 만든 데이터프레임 \n',df_arr2)


2차원 리스트로 만든 데이터프레임 
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 넘파이 배열로 만든 데이터프레임 
    col1  col2  col3
0     1     2     3
1    11    12    13


In [21]:
#딕셔너리로 데이터프레임 만들기
dict={'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict=pd.DataFrame(dict)
print('딕셔너리로 만든 데이터프레임: \n',df_dict)

딕셔너리로 만든 데이터프레임: 
    col1  col2  col3
0     1     2     3
1    11    22    33


In [23]:
#데이터프레임을 넘파이 배열이나 파이썬의 리스트, 딕셔너리로 변환하기
arr3= df_dict.values
print(arr3)

[[ 1  2  3]
 [11 22 33]]


In [26]:
lst3= df_dict.values.tolist()
print('df_dict.values.tolist()타입',type(lst3))
print(lst3)

#DataFrame을 딕셔너리로 변환
dict3= df_dict.to_dict('list')
print('\n df_dict.to_dict()타입:',type(dict3))
print(dict3)

df_dict.values.tolist()타입 <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict()타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [30]:
titanic_df= pd.read_csv('./train.csv')
titanic_df[titanic_df['Age']>60][['Name','Age']].head(5)

Name   Age
33            Wheadon, Mr. Edward H  66.0
54   Ostby, Mr. Engelhart Cornelius  65.0
96        Goldschmidt, Mr. George B  71.0
116            Connors, Mr. Patrick  70.5
170       Van der hoef, Mr. Wyckoff  61.0

In [31]:
print(dict3)
titanic_df = pd.read_csv('./train.csv')
titanic_df.loc[titanic_df['Age'] > 60][['Name', 'Age']].head(5)

{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


Name   Age
33            Wheadon, Mr. Edward H  66.0
54   Ostby, Mr. Engelhart Cornelius  65.0
96        Goldschmidt, Mr. George B  71.0
116            Connors, Mr. Patrick  70.5
170       Van der hoef, Mr. Wyckoff  61.0