In [ ]:
#데이터 핸들링 라이브러리
import numpy as np
import pandas as pd

#통계 라이브러리
from scipy import stats

#머신러닝 라이브러리
import sklearn
#정확도 측정 함수
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

#시각화 라이브러리
import matplotlib.pyplot as plt
import seaborn as sns

|## 첫번째 머신러닝 모델- 붓꽃 품종 예측

In [ ]:
# 데이터 import 하기
from sklearn.datasets import load_iris
#의사결정 트리 classifier import하기
from sklearn.tree import DecisionTreeClassifier
#훈련,테스트 세트 분리 함수 import 하기
from sklearn.model_selection import train_test_split

In [ ]:
- 분류 Classification은 대표적인 지도학습Classification Learning 방법론이다

In [ ]:
#붓꽃 데이터셋을 로딩하기
iris= load_iris()
iris_data= iris.data
#iris의 값만 가져옴
iris_data
#iris의 label: 정답값
iris_label= iris.target
print('iris target값',iris_label)
print('iris target명',iris.target_names)

#데이터프레임으로 변환하기
iris_df= pd.DataFrame(data=iris_data,columns=iris.feature_names)
iris_df['label']=iris.target
iris_df.head(10)

iris target값 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명 ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   
6                4.6               3.4                1.4               0.3   
7                5.0               3.4                1.5               0.2   
8                4.4               2.9                1.4               0.2   
9                4.9               3.1                1.5               0.1   

   label  
0      0  
1      0  
2      0  
3      0  
4      0  
5      0  
6      0  
7      0  
8      0  
9      0

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,test_size=0.2,random_state=11)
X_train

array([[5.1, 3.5, 1.4, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [5. , 3.3, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.6, 3. , 6.6, 2.1],
       [6.7, 3. , 5. , 1.7],
       [5.5, 3.5, 1.3, 0.2],
       [6. , 2.7, 5.1, 1.6],
       [5. , 2. , 3.5, 1. ],
       [7.9, 3.8, 6.4, 2. ],
       [4.6, 3.4, 1.4, 0.3],
       [6.9, 3.1, 4.9, 1.5],
       [6.5, 3. , 5.8, 2.2],
       [5.1, 2.5, 3. , 1.1],
       [6.6, 2.9, 4.6, 1.3],
       [5. , 3.2, 1.2, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.1, 3.8, 1.6, 0.2],
       [6.8, 3.2, 5.9, 2.3],
       [6.9, 3.1, 5.1, 2.3],
       [5.9, 3. , 4.2, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.7, 3.1, 4.7, 1.5],
       [4.4, 3.2, 1.3, 0.2],
       [5.4, 3.4, 1.7, 0.2],
       [6.5, 2.8, 4.6, 1.5],
       [5.1, 3.7, 1.5, 0.4],
       [5. , 3.4, 1.6, 0.4],
       [6.1, 2.6, 5.6, 1.4],
       [6.5, 3. , 5.5, 1.8],
       [6.3, 2.5, 5. , 1.9],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3

In [ ]:
#모델 생성하기
DTC= DecisionTreeClassifier(random_state=11)
#모델 학습시키기
DTC.fit(X_train,y_train)
#학습이 완료된 모델 객체와 테스트 데이터셋을 활용하여 예측하기
pred= DTC.predict(X_test)
#정확도 측정하기
print(f'예측 정확도: {accuracy_score(y_test,pred):.3f}')

예측 정확도: 0.933


In [ ]:
from sklearn.datasets import load_iris

iris_data= load_iris()
print(type(iris_data))

keys= iris_data.keys()
print('붓꽃 데이터 세트의 키들',keys)

<class 'sklearn.utils.Bunch'>
붓꽃 데이터 세트의 키들 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [ ]:
print('\n feature_names 의 type',type(iris_data.feature_names))
print('feature_names의 shape', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type',type(iris_data.target_names))
print('target_names의 shape:',len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type:', type(iris_data.data))
print('data의 shape',iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type:',type(iris_data.target))
print('target의 shape:',iris_data.target.shape)
print(iris_data.target)


 feature_names 의 type <class 'list'>
feature_names의 shape 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type <class 'numpy.ndarray'>
target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data의 type: <class 'numpy.ndarray'>
data의 shape (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


DTC= DecisionTreeClassifier()
iris_data=load_iris()
#훈련/테스트용 데이터 분리하기
X_train,X_test,y_train,y_test = train_test_split(iris_data.data,iris_data.target,test_size=0.3,random_state=121)
#모델 학습시키기
DTC.fit(X_train,y_train)
pred= DTC.predict(X_test)
print(f'예측 정확도는 {accuracy_score(y_test,pred):.4f} 입니다')

예측 정확도는 0.9556 입니다


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features= iris.data
label= iris.target
DTC= DecisionTreeClassifier(random_state=156)

#5개의 폴드 세트로 분리하는 K-Fold객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold= KFold(n_splits=5)
cv_accuracy=[]
print('붓꽃 데이터 크기:',features.shape[0])

붓꽃 데이터 크기: 150


In [ ]:
#전체 데이터는 150 => 학습은 150*4/5=120, 검증은 30
n_iter=0
# KFold 객체의 split()을 호출하면 폴드용 학습용, 검증용 테스트의 로우 인덱스를 array로 반환한다
for train_index, test_index in kfold.split(features):
    #kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test= label[train_index], label[test_index]
    #학습 및 예측
    DTC.fit(X_train,y_train)
    pred=DTC.predict(X_test)
    n_iter= n_iter+1
    #반복시마다 정확도를 측정한다
    accuracy= np.round(accuracy_score(y_test,pred),4)
    train_size= X_train.shape[0]
    test_size= X_test.shape[0]
    print(f'{n_iter} 교차 검증 정확도: {accuracy} 학습 데이터 크기: {train_size} 검증 데이터 크기{test_size}')
    print(f'{n_iter} 검증 세트 인덱스{test_index}')
    cv_accuracy.append(accuracy)

#반복할 때마다 계산된 정확도를 평균한다
print(f'평균 검증 정확도{np.mean(cv_accuracy)}')

1 교차 검증 정확도: 1.0 학습 데이터 크기: 120 검증 데이터 크기30
1 검증 세트 인덱스[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
2 교차 검증 정확도: 0.9667 학습 데이터 크기: 120 검증 데이터 크기30
2 검증 세트 인덱스[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
3 교차 검증 정확도: 0.8667 학습 데이터 크기: 120 검증 데이터 크기30
3 검증 세트 인덱스[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
4 교차 검증 정확도: 0.9333 학습 데이터 크기: 120 검증 데이터 크기30
4 검증 세트 인덱스[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
5 교차 검증 정확도: 0.7333 학습 데이터 크기: 120 검증 데이터 크기30
5 검증 세트 인덱스[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
평균 검증 정확도0.9


In [ ]:
import pandas as pd

iris= load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [ ]:
from sklearn.model_selection import StratifiedKFold

skf= StratifiedKFold(n_splits=3)
n_iter=0

#레이블 분포도에 따라 학습/검증 데이터를 나누기 때문에 split argument에 레이블 데이터도 필요하다
for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter = n_iter +1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'교차 검증: {n_iter}')
    print(f'학습 레이블 데이터 분포\n', label_train.value_counts())
    print(f'검증 레이블 데이터 분포\n', label_test.value_counts())




교차 검증: 1
학습 레이블 데이터 분포
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포
 0    17
1    17
2    16
Name: label, dtype: int64
교차 검증: 2
학습 레이블 데이터 분포
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포
 0    17
2    17
1    16
Name: label, dtype: int64
교차 검증: 3
학습 레이블 데이터 분포
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포
 1    17
2    17
0    16
Name: label, dtype: int64


In [ ]:
from sklearn.model_selection import StratifiedKFold

skf= StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

#레이블 분포도에 따라 학습/검증 데이터를 나누기 때문에 split argument에 레이블 데이터도 필요하다
for train_index, test_index in skf.split(features,label):
    #split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터를 추출하기
    X_train, X_test= features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    #학습 및 예측
    DTC.fit(X_train, y_train)
    pred= DTC.predict(X_test)

    #반복시마다 정확도 측정
    n_iter=n_iter +1
    accuracy= np.round(accuracy_score(y_test,pred),4)
    train_size= X_train.shape[0]
    test_size= X_test.shape[0]
    print(f'\n {n_iter} 교차 검증 정확도:{accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기:{test_size}')
    print(f'{n_iter} 검증 세트 인덱스 {test_index}')
    cv_accuracy.append(accuracy)

#교차 검증별 정확도 및 평균 정확도 계산
print('\n 교차 검증별 정확도:' ,np.round(cv_accuracy,4))
print('평균 검증 정확도:',np.round(np.mean(cv_accuracy),4))



 1 교차 검증 정확도:0.98, 학습 데이터 크기: 100, 검증 데이터 크기:50
1 검증 세트 인덱스 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

 2 교차 검증 정확도:0.94, 학습 데이터 크기: 100, 검증 데이터 크기:50
2 검증 세트 인덱스 [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

 3 교차 검증 정확도:0.98, 학습 데이터 크기: 100, 검증 데이터 크기:50
3 검증 세트 인덱스 [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

 교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


In [ ]:
#관련 모듈 import 하기
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris


In [ ]:
iris_data= load_iris()
DTC= DecisionTreeClassifier(random_state=156)

data= iris_data.data
label= iris_data.target

#성능 지표는 정확도(accuracy), 교차 검증 세트는 3개로 정한다
scores=cross_val_score(DTC,data,label,scoring='accuracy',cv=3)
print('교차 검증별 정확도:',np.round(scores,4))
print('평균 검증 정확도',np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도 0.9667


In [ ]:
grid_parameter= {'max_depth':[1,2,3],
                 'min_samples_split':[2,3]}

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

#데이터를 로딩하고 학습 데이터와 테스트 데이터를 분리시킨다
iris_data= load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data,iris_data.target,test_size=0.2,random_state=121)

dtree=DecisionTreeClassifier()

#하이퍼 파라미터를 딕셔너리 형태로 만든다
parameters= {'max_depth':[1,2,3],'min_samples_split':[2,3]}

#parameter_grid의 하이퍼 파라미터를 3개의 train<test set fold로 나누어 테스트를 수행한다
grid_dtree= GridSearchCV(dtree,param_grid=parameters, cv=3 ,refit=True)

#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습 및 평가
grid_dtree.fit(X_train,y_train)

#GridsearchCV 결과를 추출하여 DataFrame으로 변환시킨다
scores_df= pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

In [ ]:
#parameter_grid의 하이퍼 파라미터를 3개의 train<test set fold로 나누어 테스트를 수행한다
grid_dtree= GridSearchCV(dtree,param_grid=parameters, cv=3 ,refit=True)

#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습 및 평가
grid_dtree.fit(X_train,y_train)

#GridsearchCV 결과를 추출하여 DataFrame으로 변환시킨다
scores_df= pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [ ]:
print('GridSearchCV 최적 파라미터는 ',grid_dtree.best_params_)
print(f'GridSearchCV 최고 정확도는 {grid_dtree.best_score_:.3f}')

GridSearchCV 최적 파라미터는  {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도는 0.975


In [ ]:
#GridSearchCV의 reft으로 이미 학습된 estimator 반환시키기
estimator = grid_dtree.best_estimator_

#GridSearchCV의 best_estimator_는 이미 최적 학습이 되었으므로 별도의 학습이 필요없다
pred= estimator.predict(X_test)
print(f'테스트 데이터 셋의 정확도는 {accuracy_score(y_test,pred):.4f} 입니다')

테스트 데이터 셋의 정확도는 0.9667 입니다


In [ ]:
from sklearn.preprocessing import LabelEncoder
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩을 수행한다
encoder= LabelEncoder()
encoder.fit(items)
labels= encoder.transform(items)
print('인코딩 변환값',labels)

인코딩 변환값 [0 1 4 5 3 3 2 2]


In [ ]:
print('인코딩 클래스',encoder.classes_)

인코딩 클래스 ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [ ]:
print('디코딩 원본값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']
#2차원 넘파이 배열로 변환한다
items= np.array(items).reshape(-1,1)

#원- 핫 인코딩을 적용한다
oh_encoder= OneHotEncoder()
oh_encoder.fit(items)
oh_labels= oh_encoder.transform(items)

#OneHotEncdoer로 변환한 결과는 희소행렬이므로 toarray()를 통해 밀집 행렬로 변환할 수 있다
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [ ]:
import pandas as pd
df= pd.DataFrame({'items':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)

items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         0          1            0          0
6         0          0         1          0            0          0
7         0          0         1          0            0          0

In [ ]:
#StandardScaler
from sklearn.datasets import load_iris
import pandas as pd
#붓꽃 데이터를 로딩하고 Dataframe으로 변환한다
iris= load_iris()
iris_data= iris.data
iris_df = pd.DataFrame(data=iris_data,columns=iris.feature_names)

print(f'feature들의 평균값은 \n{iris_df.mean()}')
print(f'\nfeature들의 분산값은 \n{iris_df.var()}')

feature들의 평균값은 
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산값은 
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [ ]:
#이제 StandardScaler를 활용하여 정규화하기
from sklearn.preprocessing import StandardScaler

#StandardScaler 객체 생성하기
scaler= StandardScaler()
#StandardScaler로 데이터 세트 변환. fit() 과 trnasformation() 호출
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

#transform()시 스케일 변환된 데이터 셋이 넘파이 배열로 변환되어 이를 데이터프레임으로 변환한다
iris_df_scaled= pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print(f'features의 평군값은 \n{iris_df_scaled.mean()}\n이다')
print(f'feature들의 분산 값은 \n{iris_df_scaled.var()}\n이다')

features의 평군값은 
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
이다
feature들의 분산 값은 
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64
이다


In [ ]:
from sklearn.preprocessing import MinMaxScaler

#MinMaxScaler객체 생성하기
scaler= MinMaxScaler()
#MinMaxSclaer로 데이터 세트 변환. fit()과 transformation() 호출하기
scaler.fit(iris_df)
iris_scaled= scaler.transform(iris_df)

#transform()시 스케일 변환된 데이터 셋이 넘파이 배열로 반환되어 이를 데이터프레임으로 변환시킨다
iris_df_scaled= pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print(f'feature들의 최솟값은 \n{iris_df_scaled.min()}\n입니다')
print(f'feature들의 최댓값은 \n{iris_df_scaled.max()}\n입니다')

feature들의 최솟값은 
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
입니다
feature들의 최댓값은 
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
입니다


In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

#학습 데이터는 0~10까지, 테스트 데이터는 0~5까지 값을 갖는 데이터 셋으로 생성
#Scaler 클래스의 fit(),transform()은 2차원 이상 데이터만 사용가능 하므로 reshape(-1,1)으로 차원 변경을 한다
train_arr=np.arange(0,11).reshape(-1,1)
test_arr=np.arange(0,6).reshape(-1,1)

#MinMaxScaler 객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0~1 값으로 변환한다
scaler= MinMaxScaler()
#fit()하게 되면 train_arr 데이터 최솟값이 0, 최댓값이 10으로 설정된다
scaler.fit(train_arr)
# train_arr에 1/10을 곱한값으로 train_scaled 데이터가 변환됨.
train_scaled= scaler.transform(train_arr)

print(f'원본 train_arr 데이터는 {np.round(train_arr.reshape(-1),2)}')
print(f'scaled train_arr 데이터는 {np.round(train_scaled.reshape(-1),2)}')

원본 train_arr 데이터는 [ 0  1  2  3  4  5  6  7  8  9 10]
scaled train_arr 데이터는 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
#MinMaxScaler에 test_arr를 fit()하게 되면 원본 데이터의 최솟값이 0, 최댓값이 5로 설정됨
scaler.fit(test_arr)
#test_arr에 1/5를 곱한값으로 test_scaled가 반환됨
test_scaled= scaler.transform(test_arr)

#test_arr의 scale 변환 출력
print(f'원본 test_arr 데이터:{np.round(test_arr.reshape(-1),2)}')
print(f'scaled test_arr 데이터:{np.round(test_scaled.reshape(-1),2)}')

원본 test_arr 데이터:[0 1 2 3 4 5]
scaled test_arr 데이터:[0.  0.2 0.4 0.6 0.8 1. ]


## 사이킷런으로 수행하는 타이타닉 생존 예측

- passengerid: 탑승자 데이터 일련번호
- survived: 생존 여부 0: 사망, 1: 생존
- pclass: 티켓의 선실 등급 1:1등석, 2:2등석 3:3등석
- sex: 탑승자 성별
- name: 탑승자 이름
- age: 탑승자 나이
- sibsp: 같이 탑승한 형제자매 또는 배우자의 인원수
- parch:같이 탑승한 부모님 또는 어린이 인원 수
- ticket: 티켓 번호
- fare: 요금
- cabin: 선실번호
- embarked:중간 정착 항구

In [ ]:
df_titanic= pd.read_csv('./train.csv')
df_titanic.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [ ]:
#데이터 정보 확인하기
print(df_titanic.shape) # 891 * 12: 데이터 891개, 컬럼 12개
df_titanic.info()

(891, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [ ]:
#결측치 확인하기 => Age 177, Cabin 687개 Embarked 2개이다
df_titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
#기술 통계량 확인하기
df_stats= df_titanic.describe().T
df_stats

count        mean         std   min       25%       50%    75%  \
PassengerId  891.0  446.000000  257.353842  1.00  223.5000  446.0000  668.5   
Survived     891.0    0.383838    0.486592  0.00    0.0000    0.0000    1.0   
Pclass       891.0    2.308642    0.836071  1.00    2.0000    3.0000    3.0   
Age          714.0   29.699118   14.526497  0.42   20.1250   28.0000   38.0   
SibSp        891.0    0.523008    1.102743  0.00    0.0000    0.0000    1.0   
Parch        891.0    0.381594    0.806057  0.00    0.0000    0.0000    0.0   
Fare         891.0   32.204208   49.693429  0.00    7.9104   14.4542   31.0   

                  max  
PassengerId  891.0000  
Survived       1.0000  
Pclass         3.0000  
Age           80.0000  
SibSp          8.0000  
Parch          6.0000  
Fare         512.3292

## 데이터 전처리 계획
- 결측치 처리하기
- 문자열-카테고리 변수 인코딩 하기
- 피쳐 스케일링 하기
- 불필요해보이는 피처 제거하기
## 학습 계획
- 훈련, 테스트 데이터 분리(이미 분리된 데이터를 제공받음)
- 모델 세우기
- 학습 및 평가
# 분석 계획
- 그래프 시각화
- 증거를 기반으로 한 추론 제시

In [ ]:
# 결측치 처리하기
# 이 책에선 age는 열의 평균으로, 나머지 변수들은 'N'값으로 체우기로 결정한다
df_titanic['Age'].fillna(df_titanic['Age'].mean(),inplace=True)
df_titanic['Cabin'].fillna('N',inplace=True)
df_titanic['Embarked'].fillna('N',inplace=True)
print(f'데이터 셋 Null값 개수는 {df_titanic.isnull().sum().sum()}개 입니다')

데이터 셋 Null값 개수는 0개 입니다


In [ ]:
#문자열- 카테고리 피처 Sex,Cabin,Embarked를 인코딩하기
from sklearn.preprocessing import LabelEncoder

#한번만 인코딩해야됨. 두번하면 안됨
categories_backup=[]
features=['Cabin','Sex','Embarked']
for feature in features:
    LE= LabelEncoder()
    LE= LE.fit(df_titanic[feature])
    #카테고리 백업해두기
    categories_backup.append(list(LE.classes_))
    #인코딩하기
    df_titanic[feature]= LE.transform(df_titanic[feature])

df_titanic.head(10)
print(categories_backup)

[['A10', 'A14', 'A16', 'A19', 'A20', 'A23', 'A24', 'A26', 'A31', 'A32', 'A34', 'A36', 'A5', 'A6', 'A7', 'B101', 'B102', 'B18', 'B19', 'B20', 'B22', 'B28', 'B3', 'B30', 'B35', 'B37', 'B38', 'B39', 'B4', 'B41', 'B42', 'B49', 'B5', 'B50', 'B51 B53 B55', 'B57 B59 B63 B66', 'B58 B60', 'B69', 'B71', 'B73', 'B77', 'B78', 'B79', 'B80', 'B82 B84', 'B86', 'B94', 'B96 B98', 'C101', 'C103', 'C104', 'C106', 'C110', 'C111', 'C118', 'C123', 'C124', 'C125', 'C126', 'C128', 'C148', 'C2', 'C22 C26', 'C23 C25 C27', 'C30', 'C32', 'C45', 'C46', 'C47', 'C49', 'C50', 'C52', 'C54', 'C62 C64', 'C65', 'C68', 'C7', 'C70', 'C78', 'C82', 'C83', 'C85', 'C86', 'C87', 'C90', 'C91', 'C92', 'C93', 'C95', 'C99', 'D', 'D10 D12', 'D11', 'D15', 'D17', 'D19', 'D20', 'D21', 'D26', 'D28', 'D30', 'D33', 'D35', 'D36', 'D37', 'D45', 'D46', 'D47', 'D48', 'D49', 'D50', 'D56', 'D6', 'D7', 'D9', 'E10', 'E101', 'E12', 'E121', 'E17', 'E24', 'E25', 'E31', 'E33', 'E34', 'E36', 'E38', 'E40', 'E44', 'E46', 'E49', 'E50', 'E58', 'E63', 'E67

In [ ]:
#인코딩한 데이터 백업해보기
LE= LabelEncoder()
LE=LE.fit(categories_backup[1])
LE.inverse_transform(df_titanic['Sex'])

array(['male', 'female', 'female', 'female', 'male', 'male', 'male',
       'male', 'female', 'female', 'female', 'female', 'male', 'male',
       'female', 'female', 'male', 'male', 'female', 'female', 'male',
       'male', 'female', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'male', 'male', 'male', 'female', 'female', 'female', 'female',
       'male', 'female', 'female', 'male', 'male', 'female', 'male',
       'female', 'male', 'male', 'female', 'female', 'male', 'male',
       'female', 'male', 'female', 'male', 'male', 'female', 'male',
       'male', 'male', 'male', 'female', 'male', 'female', 'male', 'male',
       'female', 'male', 'male', 'male', 'male', 'male', 'male', 'male',
       'female', 'male', 'male', 'female', 'male', 'female', 'female',
       'male', 'male', 'female', 'male', 'male', 'male', 'male', 'male',
       'male', 'male', 'male', 'male', 'female', 'male', 'female', 'male',
      

In [ ]:
#불필요해보이는 피처 제거하기
df_titanic.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

In [ ]:
df_titanic

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [ ]:
#데이터 전처리: Null값 처리/ 불필요 피처 제거/ 문자열-카테고리 인코딩을 일괄적으로 수행할 수 있겠끔 함수로 만들기

# 결측치 처리하기
def fillna(df):
    # 이 책에선 age는 열의 평균으로, 나머지 변수들은 'N'값으로 체우기로 결정한다
    df['Age'].fillna(df['Age'].mean(),inplace=True)
    df['Cabin'].fillna('N',inplace=True)
    df['Embarked'].fillna('N',inplace=True)
    return df

#불필요해보이는 피처 제거하기
def drop_features(df):
    df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)
    return df

#문자열- 카테고리 피처 Sex,Cabin,Embarked를 인코딩하기
def encoding_features(df):
    #한번만 인코딩해야됨. 두번하면 안됨
    categories_backup=[]
    features=['Cabin','Sex','Embarked']
    for feature in features:
        LE= LabelEncoder()
        LE= LE.fit(df[feature])
        #카테고리 백업해두기
        categories_backup.append(list(LE.classes_))
        #인코딩하기
        df[feature]= LE.transform(df[feature])
    return df

#앞에서 정의한 전처리 함수들을 호출하여 한번에 전처리를 완료하기
def preprocessing_feature(df):
    df= fillna(df)
    df= drop_features(df)
    df= encoding_features(df)
    return df


df_titanic= pd.read_csv('./train.csv')
y_titanic_df= df_titanic['Survived']
X_titanic_df= df_titanic.drop('Survived',axis=1)
X_titanic_df= preprocessing_feature(X_titanic_df)

In [ ]:
y_titanic_df

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [ ]:
X_titanic_df.groupby('Cabin').count()

Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
Cabin                                                
0           1    1    1      1      1     1         1
1           1    1    1      1      1     1         1
2           1    1    1      1      1     1         1
3           1    1    1      1      1     1         1
4           1    1    1      1      1     1         1
...       ...  ...  ...    ...    ...   ...       ...
143         1    1    1      1      1     1         1
144         2    2    2      2      2     2         2
145         4    4    4      4      4     4         4
146       687  687  687    687    687   687       687
147         1    1    1      1      1     1         1

[148 rows x 7 columns]

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#결정트리, Random Forest, 로지스틱 회귀를 위한 사이킷런 Classifier 클래스 생성
DTC= DecisionTreeClassifier(random_state=11)
RFC= RandomForestClassifier(random_state=11)
LR= LogisticRegression(solver='liblinear')

#DecisionTreeClassifier 학습/예측/평가
DTC.fit(X_train,y_train)
DT_pred=DTC.predict(X_test)
print(f'DecisionTreeClassifier 정확도는 {accuracy_score(y_test,DT_pred):.4f}')

#RandomForestClassifier 학습/예측/평가
RFC.fit(X_train,y_train)
RF_pred= RFC.predict(X_test)
print(f'RandomForestClassifier 정확도는 {accuracy_score(y_test,RF_pred):.4f}')

#LogisticRegression 학습/예측/평가
LR.fit(X_train,y_train)
LR_pred= LR.predict(X_test)
print(f'LogisticRegression 정확도는 {accuracy_score(y_test,LR_pred):.4f}')

DecisionTreeClassifier 정확도는 0.9667
RandomForestClassifier 정확도는 0.9667
LogisticRegression 정확도는 0.9000


In [ ]:
from sklearn.model_selection import KFold

def cal_fold(clf,folds=5):
    kfold=KFold(n_splits=folds)
    scores=[]

    #KFold 교차 검증 수행
    for iter_count, (train_index,test_index) in enumerate(kfold.split(X_titanic_df)):
        # X_titanic_df 데이터에서 교차 검증별로 학습 과 검증 데이터를 가리키는 index를 생성한다
        X_train,X_test= X_titanic_df.values[train_index],X_titanic_df.values[test_index]
        y_train, y_test = y_titanic_df.values[train_index], y_titanic_df.values[test_index]
        #classifier 학습,예측,정확도 계산
        clf.fit(X_train,y_train)
        predictions= clf.predict(X_test)
        accuracy= accuracy_score(y_test,predictions)
        scores.append(accuracy)
        print(f'교차 검증 {iter_count:.4f} 정확도 {accuracy:.4f} ')

    #5개 fold에서의 평균 정확도 계산
    mean_score= np.mean(scores)
    print(f'평균 정확도는 {mean_score:.4f}')
#cal_fold 함수 호출
cal_fold(DTC,folds=5)

교차 검증 0.0000 정확도 0.7486 
교차 검증 1.0000 정확도 0.7640 
교차 검증 2.0000 정확도 0.8202 
교차 검증 3.0000 정확도 0.7809 
교차 검증 4.0000 정확도 0.7921 
평균 정확도는 0.7812


In [ ]:
#이 교차검증 함수는 StratifiedKFold를 통해 폴드 세트를 분할한다
from sklearn.model_selection import cross_val_score

scores= cross_val_score(DTC,X_titanic_df,y_titanic_df,cv=5)
for iter_count, accuracy in enumerate(scores):
    print(f'교차 검증 {iter_count:.4f} 정확도: {accuracy:.4f}')

print(f'평균 정확도: {np.mean(scores):.4f}')

교차 검증 0.0000 정확도: 0.7486
교차 검증 1.0000 정확도: 0.7753
교차 검증 2.0000 정확도: 0.8090
교차 검증 3.0000 정확도: 0.7584
교차 검증 4.0000 정확도: 0.8034
평균 정확도: 0.7789


In [ ]:
#GridSearchCV를 통해 DecisionTreeClassifier의 최적 하이퍼 파라미터 성능을 측적하기
from sklearn.model_selection import GridSearchCV

parameters={'max_depth':[2,3,5,10],
            'min_samples_split':[2,3,5], 'min_samples_leaf':[1,5,8]}

grid_dclf= GridSearchCV(DTC, param_grid=parameters, scoring='accuracy',cv=5)
grid_dclf.fit(X_train,y_train)

print(f'GridSearchCV 최적 하이퍼 파라미터: {grid_dclf.best_params_}')
print(f'GridSearchCV 최고의 정확도:{grid_dclf.best_score_}')
best_dlcf= grid_dclf.best_estimator_

#GridSearchCV의 최적 하이퍼파라미터로 학습된 Estimator로 예측 및 평가 수행
dpredictions= best_dlcf.predict(X_test)
accuracy=accuracy_score(y_test,dpredictions)
print(f'테스트 세트에서의 DecisionTreeClassifier 정확도는 {accuracy:.4f}')

GridSearchCV 최적 하이퍼 파라미터: {'max_depth': 3, 'min_samples_leaf': 1, 'min_samples_split': 2}
GridSearchCV 최고의 정확도:0.975
테스트 세트에서의 DecisionTreeClassifier 정확도는 0.9667


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=59f71f48-e620-40de-82b6-60c121211e54' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>